Consumable[] =
{
/*	{Loot_MAGAZINE,		8,		ItemBandage},
	{Loot_MAGAZINE,		4,		ItemHeatPack},
	{Loot_MAGAZINE,		3,		ItemPainkiller},
	{Loot_MAGAZINE,		3,		ItemAntibacterialWipe},*/
	
	{Loot_MAGAZINE,		10,		ItemWaterBottleUnfilled}, //TODO: replace with canteen to better fit Epoch lootPosSmall
	{Loot_MAGAZINE,		10,		ItemWaterBottleSafe},
	{Loot_MAGAZINE,		10,		ItemWaterBottle},
	{Loot_MAGAZINE,		10,		ItemHeatPack},
	
	{Loot_MAGAZINE,		10,		ItemSodaCoke},
	{Loot_MAGAZINE,		10,		ItemSodaPepsi},
	{Loot_MAGAZINE,		10,		ItemSodaMdew},
	{Loot_MAGAZINE,		10,		ItemSodaRbull},
	{Loot_MAGAZINE,		10,		ItemSodaOrangeSherbet},

	{Loot_MAGAZINE,		10,		ItemSodaMtngreen},
	{Loot_MAGAZINE,		10,		ItemSodaR4z0r},
	{Loot_MAGAZINE,		10,		ItemSodaClays},
	{Loot_MAGAZINE,		10,		ItemSodaSmasht},
	{Loot_MAGAZINE,		10,		ItemSodaDrwaste},
	{Loot_MAGAZINE,		10,		ItemSodaFranka},
	{Loot_MAGAZINE,		10,		ItemSodaLemonade},
	{Loot_MAGAZINE,		10,		ItemSodaLirik},
	{Loot_MAGAZINE,		10,		ItemSodaLvg},
	{Loot_MAGAZINE,		10,		ItemSodaMzly},
	{Loot_MAGAZINE,		10,		ItemSodaPeppsy},
	{Loot_MAGAZINE,		10,		ItemSodaRabbit},
	{Loot_MAGAZINE,		10,		ItemSodaSacrite},
	{Loot_MAGAZINE,		10,		ItemSodaRocketFuel},
	{Loot_MAGAZINE,		10,		ItemSodaGrapeDrink},
	{Loot_MAGAZINE,		10,		ItemSherbet},
	
	{Loot_MAGAZINE,		10,		FoodPistachio},
	{Loot_MAGAZINE,		10,		FoodNutmix},
	{Loot_MAGAZINE,		10,		FoodChipsSulahoops},
	{Loot_MAGAZINE,		10,		FoodChipsMysticales},
	{Loot_MAGAZINE,		10,		FoodChipsChocolate},
	{Loot_MAGAZINE,		10,		FoodCandyChubby},
	{Loot_MAGAZINE,		10,		FoodCandyAnders},
	{Loot_MAGAZINE,		10,		FoodCandyLegacys},
	{Loot_MAGAZINE,		10,		FoodCandyMintception},
	{Loot_MAGAZINE,		10,		FoodCakeCremeCakeClean},
	
	{Loot_MAGAZINE,		10,		FoodCanBeef},
	{Loot_MAGAZINE,		10,		FoodCanPotatoes},
	{Loot_MAGAZINE,		10,		FoodCanGriff},
	{Loot_MAGAZINE,		10,		FoodCanBadguy},
	{Loot_MAGAZINE,		10,		FoodCanBoneboy},
	{Loot_MAGAZINE,		10,		FoodCanCorn},
	{Loot_MAGAZINE,		10,		FoodCanCurgon},
	{Loot_MAGAZINE,		10,		FoodCanDemon},
	{Loot_MAGAZINE,		10,		FoodCanFraggleos},
	{Loot_MAGAZINE,		10,		FoodCanHerpy},
	{Loot_MAGAZINE,		10,		FoodCanDerpy},
	{Loot_MAGAZINE,		10,		FoodCanOrlok},
	{Loot_MAGAZINE,		10,		FoodCanPowell},
	{Loot_MAGAZINE,		10,		FoodCanTylers},
	
	{Loot_MAGAZINE,		10,		FoodCanUnlabeled},
	{Loot_MAGAZINE,		10,		FoodCanBakedBeans},
	{Loot_MAGAZINE,		10,		FoodCanSardines},
	{Loot_MAGAZINE,		10,		FoodCanFrankBeans},
	{Loot_MAGAZINE,		10,		FoodCanPasta},
	{Loot_MAGAZINE,		10,		FoodBioMeat},
	
	{Loot_MAGAZINE,		10,		FoodCanRusUnlabeled},
	{Loot_MAGAZINE,		10,		FoodCanRusStew},
	{Loot_MAGAZINE,		10,		FoodCanRusPork},
	{Loot_MAGAZINE,		10,		FoodCanRusPeas},
	{Loot_MAGAZINE,		10,		FoodCanRusMilk},
	{Loot_MAGAZINE,		10,		FoodCanRusCorn}
};